---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    - name: post_id
      in: path
      required: true
      schema:
        type: integer
    - name: comment
      in: body
      schema:
        type: object
        properties:
          text:
            type: string
        required:
        - text
    post:
      summary: Creates a comment
      tags:
      - Comments
      security:
      - Bearer: []
      responses:
        '201':
          description: comment created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  text:
                    type: string
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
                required:
                - id
                - text
                - created_at
                - updated_at
        '422':
          description: unprocessable entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: string
                required:
                - errors
  "/users/{user_id}/posts/{post_id}/comments":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    - name: post_id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: List all comments for a user's post
      tags:
      - Comments
      responses:
        '200':
          description: list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    text:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - text
                  - created_at
                  - updated_at
  "/users/{user_id}/posts":
    parameters:
    - name: user_id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: List all posts for a user
      tags:
      - Posts
      responses:
        '200':
          description: list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    text:
                      type: string
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time
                  required:
                  - id
                  - title
                  - text
                  - created_at
                  - updated_at
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
